# 最初に

In [4]:
# Numpy と Pandas を読み込む（全てのコードにおまじないとして書いておいて損はない）
import numpy as np
import pandas as pd

# 行列の作成

In [26]:
# 行列を作る
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [197]:
# 零行列を作る
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [199]:
# 全ての要素が 1 の行列を作る
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [200]:
# 単位行列を作る
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [271]:
# 配列を作る
np.array([1,5,7,2])

array([1, 5, 7, 2])

In [272]:
# 0 から 9 までの配列を作る 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
# 2 から 12 まで、2 ずつ増えていく配列を作る
np.arange(2, 14, 2)

array([ 2,  4,  6,  8, 10, 12])

In [27]:
# 行列を転置させる
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 行列の基本計算

In [28]:
# 行列同士の計算
B = np.array([[2,4,6],[7,8,9]])
A + B

array([[ 3,  6,  9],
       [11, 13, 15]])

In [29]:
# 掛け算は要素毎に行われる
A * B

array([[ 2,  8, 18],
       [28, 40, 54]])

In [264]:
# 全ての要素を 2 倍する
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [266]:
# 全ての要素を 3 で割る
A / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [268]:
# いくつまで割り切れるか
A // 3

array([[0, 0, 1],
       [1, 1, 2]])

In [269]:
# 余り
A % 3

array([[1, 2, 0],
       [1, 2, 0]])

In [267]:
# 四捨五入して整数で丸める
np.round(A / 3)

array([[0., 1., 1.],
       [1., 2., 2.]])

In [265]:
# 各要素の二乗
A ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
# 線形代数の行列の掛け算は matrix 型を使う
Amat = np.matrix(A)
Bmat = np.matrix(B.T)
Amat * Bmat

matrix([[ 28,  50],
        [ 64, 122]])

# 要素の選択

In [38]:
# 行列の要素を取り出す。Python の場合 0 始まり
A[0,0]

1

In [39]:
A[0,1]

2

In [34]:
#  行全体を取り出す
A[:,0]

array([1, 4])

In [37]:
#  列全体を取り出す
A[1,:]

array([4, 5, 6])

# 基本的な関数

In [290]:
# 指数
np.exp(1)

2.718281828459045

In [291]:
# 自然対数
np.log(2)

0.6931471805599453

In [292]:
# 常用対数
np.log10(2)

0.3010299956639812

In [294]:
# 三角関数
print(np.sin(3.1415))
print(np.cos(3.1415))
print(np.tan(3.1415))

9.265358966049024e-05
-0.9999999957076562
-9.265359005819131e-05


In [279]:
# 各要素の絶対値
np.abs(np.array([[-1,2],[3,-4]]))

array([[1, 2],
       [3, 4]])

# 基本的な統計量

In [40]:
# 最大値を取り出す
np.max(A)

6

In [43]:
# 各列の最大値を取り出す ( 行を足してく )
np.max(A, 0)

array([4, 5, 6])

In [44]:
# 各行の最大値を取り出す ( 列を足してく )
np.max(A, 1)

array([3, 6])

In [47]:
# 最小値も同様に出せる
print(np.min(A))
print(np.min(A, 0))
print(np.min(A, 1))

1
[1 2 3]
[1 4]


In [48]:
# 平均値や標準偏差も同様に出せる
print(np.mean(A))
print(np.mean(A, 0))
print(np.mean(A, 1))

print(np.std(A))
print(np.std(A, 0))
print(np.std(A, 1))

3.5
[2.5 3.5 4.5]
[2. 5.]
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [49]:
# 中央値
np.median(A)

3.5

In [336]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [337]:
# 各行間の相関係数を算出
np.corrcoef(A)

array([[1., 1.],
       [1., 1.]])

In [338]:
# 各列間の相関係数を算出
np.corrcoef(A, rowvar = False)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 行列の大きさ

In [253]:
# 行列のサイズを出力
A.shape

(2, 3)

In [254]:
# 行だけ、列だけ表示
A.shape[0]

2

In [55]:
# 行列を縦方向に結合
C = np.vstack((A, B))
C

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [7, 8, 9]])

In [50]:
# 行列を横方向に結合
np.hstack((A, B))

array([[1, 2, 3, 2, 4, 6],
       [4, 5, 6, 7, 8, 9]])

In [281]:
# 行列の行と列の値を変更
np.reshape(C, (6,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [2, 4],
       [6, 7],
       [8, 9]])

# 乱数

In [88]:
# ランダムに 0 から 1 までの数値を発生
np.random.rand()

0.7021123813648541

In [98]:
# シード値を設定すると、乱数を固定できる
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [196]:
# 指定した範囲の整数のみを発生。第一引数の値は現れるが、第二引数の値は現れないことに注意。
np.random.randint(0, 10)

1

In [235]:
# 標準正規分布（平均 0、標準偏差 1 ） に従い乱数を生成
np.random.randn()

-0.5384681601851071

In [241]:
# 乱数を複数発生
np.random.rand(3)

array([0.47013219, 0.71607453, 0.287991  ])

In [252]:
# 各要素の値がランダムとなる行列の作成
np.random.randn(3,4)

array([[-1.56437025, -1.73374197, -0.61556428, -0.95463388],
       [-0.24880494, -0.05508758,  0.28206989, -1.89431807],
       [ 0.83831078, -0.41631215,  1.35692793, -1.19765944]])

# 行列の要素選択と操作

In [257]:
# 上三角行列
np.random.seed(1)
D = np.random.randn(5,5)
np.triu(D)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [ 0.        ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 0.        ,  0.        , -0.3224172 , -0.38405435,  1.13376944],
       [ 0.        ,  0.        ,  0.        ,  0.04221375,  0.58281521],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.90085595]])

In [259]:
# 対角要素も 0 にする
np.triu(D, k = 1)

array([[ 0.        , -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [ 0.        ,  0.        , -0.7612069 ,  0.3190391 , -0.24937038],
       [ 0.        ,  0.        ,  0.        , -0.38405435,  1.13376944],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.58281521],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [258]:
# 下三角行列
np.tril(D)

array([[ 1.62434536,  0.        ,  0.        ,  0.        ,  0.        ],
       [-2.3015387 ,  1.74481176,  0.        ,  0.        ,  0.        ],
       [ 1.46210794, -2.06014071, -0.3224172 ,  0.        ,  0.        ],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.        ],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [260]:
# 上から3行目までを選択
D[:3, :]

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944]])

In [262]:
# 2 行目から 4 行目までを選択
D[1:4, :]

array([[-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521]])

In [263]:
# 一番下の行を選択
D[-1, :]

array([-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595])

In [270]:
# 一列目と3列目と5列目だけを選択
D[:,[0,2,4]]

array([[ 1.62434536, -0.52817175,  0.86540763],
       [-2.3015387 , -0.7612069 , -0.24937038],
       [ 1.46210794, -0.3224172 ,  1.13376944],
       [-1.09989127, -0.87785842,  0.58281521],
       [-1.10061918,  0.90159072,  0.90085595]])

In [296]:
# 一列目の値が 0 以上の行だけを取り出す
D[D[:,0] >= 0, :]

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944]])

In [307]:
#  各列毎に、値が小さい順に並べ替える
np.sort(D,0)

array([[-2.3015387 , -2.06014071, -0.87785842, -1.07296862, -0.24937038],
       [-1.10061918, -0.61175641, -0.7612069 , -0.38405435,  0.58281521],
       [-1.09989127, -0.17242821, -0.52817175,  0.04221375,  0.86540763],
       [ 1.46210794,  1.14472371, -0.3224172 ,  0.3190391 ,  0.90085595],
       [ 1.62434536,  1.74481176,  0.90159072,  0.50249434,  1.13376944]])

In [308]:
# 大きい順に並べ替える
np.sort(D,0)[::-1]

array([[ 1.62434536,  1.74481176,  0.90159072,  0.50249434,  1.13376944],
       [ 1.46210794,  1.14472371, -0.3224172 ,  0.3190391 ,  0.90085595],
       [-1.09989127, -0.17242821, -0.52817175,  0.04221375,  0.86540763],
       [-1.10061918, -0.61175641, -0.7612069 , -0.38405435,  0.58281521],
       [-2.3015387 , -2.06014071, -0.87785842, -1.07296862, -0.24937038]])

In [321]:
# 各列毎の要素の大きさを大きい順に行番号で表示
np.argsort(D,0)

array([[1, 2, 3, 0, 1],
       [4, 0, 1, 2, 3],
       [3, 3, 0, 3, 0],
       [2, 4, 2, 1, 4],
       [0, 1, 4, 4, 2]])

In [324]:
# 小さい順
np.argsort(-D,0)

array([[0, 1, 4, 4, 2],
       [2, 4, 2, 1, 4],
       [3, 3, 0, 3, 0],
       [4, 0, 1, 2, 3],
       [1, 2, 3, 0, 1]])

In [327]:
# 要素を変更
E = D
E[0, 0] = 1
E

array([[ 1.        , -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  2.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [328]:
E[1,1] += 10
E

array([[ 1.        , -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 , 12.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595]])

In [329]:
E[:, 2] = 2
E

array([[ 1.        , -0.61175641,  2.        , -1.07296862,  0.86540763],
       [-2.3015387 , 12.74481176,  2.        ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071,  2.        , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821,  2.        ,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  2.        ,  0.50249434,  0.90085595]])

In [343]:
E[3,:] = [3,4,5,6,7]
E

array([[ 1.        , -0.61175641,  2.        , -1.07296862,  0.86540763],
       [-2.3015387 , 12.74481176,  2.        ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071,  2.        , -0.38405435,  1.13376944],
       [ 3.        ,  4.        ,  5.        ,  6.        ,  7.        ],
       [-1.10061918,  1.14472371,  2.        ,  0.50249434,  0.90085595]])

# NumPy データの保存と読み込み

In [331]:
# 行列を npy 形式で出力
np.save("hoge_np.npy", E)

In [332]:
# npy 形式のデータを読み込む
data = np.load("hoge_np.npy")
data

array([[ 1.        , -0.61175641,  2.        , -1.07296862,  0.86540763],
       [-2.3015387 , 12.74481176,  2.        ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071,  2.        , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821,  2.        ,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  2.        ,  0.50249434,  0.90085595]])

# CSV データの読み込み

In [353]:
# CSV データを読み込む
df = pd.read_csv("../Documents/dataset/cafe.csv", index_col = 0)
df

Price  Volume  Sales
Cocoa           450     300      5
Cappuccino      400     250     10
Darjeeling      450     230      7
Gyokuro         470     320      3
Kona            470     250      4
Espresso        420     260      7
Kilimanjaro     500     250      8
BlueMountain    480     250      6
Brazil          550     200      3
Geisha          600     200      2
CafeAuLait      400     320      6
EarlGrey        450     250      3
Ceylon          520     250      2

In [355]:
# 一番上の行もデータとして使う場合
df = pd.read_csv("../Documents/dataset/cafe.csv", header = None)
df

0      1       2      3
0            NaN  Price  Volume  Sales
1          Cocoa    450     300      5
2     Cappuccino    400     250     10
3     Darjeeling    450     230      7
4        Gyokuro    470     320      3
5           Kona    470     250      4
6       Espresso    420     260      7
7    Kilimanjaro    500     250      8
8   BlueMountain    480     250      6
9         Brazil    550     200      3
10        Geisha    600     200      2
11    CafeAuLait    400     320      6
12      EarlGrey    450     250      3
13        Ceylon    520     250      2

In [356]:
# 一番左の列もデータとして使う場合
df = pd.read_csv("../Documents/dataset/cafe.csv")
df

Unnamed: 0  Price  Volume  Sales
0          Cocoa    450     300      5
1     Cappuccino    400     250     10
2     Darjeeling    450     230      7
3        Gyokuro    470     320      3
4           Kona    470     250      4
5       Espresso    420     260      7
6    Kilimanjaro    500     250      8
7   BlueMountain    480     250      6
8         Brazil    550     200      3
9         Geisha    600     200      2
10    CafeAuLait    400     320      6
11      EarlGrey    450     250      3
12        Ceylon    520     250      2

In [406]:
df = pd.read_csv("../Documents/dataset/cafe.csv", index_col = 0)
df_2 = pd.read_csv("../Documents/dataset/cafe2.csv", index_col = 0)
df_3 = pd.read_csv("../Documents/dataset/cafe3.csv", index_col = 0)

In [454]:
# データを numpy 形式に変換する
df_array = np.array(df)
df_array

array([[450, 300,   5],
       [400, 250,  10],
       [450, 230,   7],
       [470, 320,   3],
       [470, 250,   4],
       [420, 260,   7],
       [500, 250,   8],
       [480, 250,   6],
       [550, 200,   3],
       [600, 200,   2],
       [400, 320,   6],
       [450, 250,   3],
       [520, 250,   2]])

In [455]:
# Numpy 形式をデータフレームにする
pd.DataFrame(df_array)

0    1   2
0   450  300   5
1   400  250  10
2   450  230   7
3   470  320   3
4   470  250   4
5   420  260   7
6   500  250   8
7   480  250   6
8   550  200   3
9   600  200   2
10  400  320   6
11  450  250   3
12  520  250   2

# 要素の抽出

In [366]:
# 各行と列の名称から要素を抽出
df.loc["Cocoa", "Price"]

450

In [367]:
# 各行と列のインデックスから要素を抽出
df.iloc[0, 1]

300

In [368]:
# 列の選択
df["Price"]

Cocoa           450
Cappuccino      400
Darjeeling      450
Gyokuro         470
Kona            470
Espresso        420
Kilimanjaro     500
BlueMountain    480
Brazil          550
Geisha          600
CafeAuLait      400
EarlGrey        450
Ceylon          520
Name: Price, dtype: int64

In [369]:
# 任意の列を指定した順番に取り出す
df[["Sales", "Volume"]]

Sales  Volume
Cocoa             5     300
Cappuccino       10     250
Darjeeling        7     230
Gyokuro           3     320
Kona              4     250
Espresso          7     260
Kilimanjaro       8     250
BlueMountain      6     250
Brazil            3     200
Geisha            2     200
CafeAuLait        6     320
EarlGrey          3     250
Ceylon            2     250

In [396]:
# 列のラベル名を取り出す
df.columns

Index(['Price', 'Volume', 'Sales'], dtype='object')

In [397]:
# 行のラベル名を取り出す
df.index

Index(['Cocoa', 'Cappuccino', 'Darjeeling', 'Gyokuro', 'Kona', 'Espresso',
       'Kilimanjaro', 'BlueMountain', 'Brazil', 'Geisha', 'CafeAuLait',
       'EarlGrey', 'Ceylon'],
      dtype='object')

In [479]:
# データの上 3 行だけを表示
df.head(3)

Price  Volume  Sales
Cocoa         450     300      5
Cappuccino    400     250     10
Darjeeling    450     230      7

In [480]:
# データの下 7 行だけを表示
df.tail(7)

Price  Volume  Sales
Kilimanjaro     500     250      8
BlueMountain    480     250      6
Brazil          550     200      3
Geisha          600     200      2
CafeAuLait      400     320      6
EarlGrey        450     250      3
Ceylon          520     250      2

# データフレームの結合と切断

In [394]:
# 横方向に行列を追加
pd.concat([df, df_2], axis = 1)

Price  Volume  Sales  Coffee  Peak    WithMeal
Cocoa           450     300      5     0.0    15    Sandwich
Cappuccino      400     250     10     1.0    15  Cheesecake
Darjeeling      450     230      7     0.0    13    Sandwich
Gyokuro         470     320      3     0.0    13    Sandwich
Kona            470     250      4     1.0    14   Montblank
Espresso        420     260      7     1.0  None  Cheesecake
Kilimanjaro     500     250      8     1.0    16   Montblank
BlueMountain    480     250      6     1.0    16   Montblank
Brazil          550     200      3     1.0  None   Montblank
Geisha          600     200      2     1.0  None  Cheesecake
CafeAuLait      400     320      6     1.0    14   Montblank
EarlGrey        450     250      3     0.0    15    Sandwich
Ceylon          520     250      2     0.0    14   Montblank

In [395]:
# 縦方向に行列を追加
pd.concat([df, df_3])

Price  Volume  Sales
Cocoa           450     300      5
Cappuccino      400     250     10
Darjeeling      450     230      7
Gyokuro         470     320      3
Kona            470     250      4
Espresso        420     260      7
Kilimanjaro     500     250      8
BlueMountain    480     250      6
Brazil          550     200      3
Geisha          600     200      2
CafeAuLait      400     320      6
EarlGrey        450     250      3
Ceylon          520     250      2
Genmaicha       450     320      4
CafeMocha       420     300      8
Nilgiri         500     250      2

# 欠損値の処理

In [408]:
# 欠損値が一つでもある特徴量（列）を削除
A = pd.concat([df, df_2], axis = 1)
A.dropna(axis = 1)

Price  Volume  Sales  Coffee    WithMeal
Cocoa           450     300      5     0.0    Sandwich
Cappuccino      400     250     10     1.0  Cheesecake
Darjeeling      450     230      7     0.0    Sandwich
Gyokuro         470     320      3     0.0    Sandwich
Kona            470     250      4     1.0   Montblank
Espresso        420     260      7     1.0  Cheesecake
Kilimanjaro     500     250      8     1.0   Montblank
BlueMountain    480     250      6     1.0   Montblank
Brazil          550     200      3     1.0   Montblank
Geisha          600     200      2     1.0  Cheesecake
CafeAuLait      400     320      6     1.0   Montblank
EarlGrey        450     250      3     0.0    Sandwich
Ceylon          520     250      2     0.0   Montblank

In [414]:
# 全てのデータが欠損値である特徴量（列）を削除
A = pd.concat([df, df_2], axis = 1)
B = A.dropna(how = "all", axis = 1)
B

Price  Volume  Sales  Coffee  Peak    WithMeal
Cocoa           450     300      5     0.0  15.0    Sandwich
Cappuccino      400     250     10     1.0  15.0  Cheesecake
Darjeeling      450     230      7     0.0  13.0    Sandwich
Gyokuro         470     320      3     0.0  13.0    Sandwich
Kona            470     250      4     1.0  14.0   Montblank
Espresso        420     260      7     1.0   NaN  Cheesecake
Kilimanjaro     500     250      8     1.0  16.0   Montblank
BlueMountain    480     250      6     1.0  16.0   Montblank
Brazil          550     200      3     1.0   NaN   Montblank
Geisha          600     200      2     1.0   NaN  Cheesecake
CafeAuLait      400     320      6     1.0  14.0   Montblank
EarlGrey        450     250      3     0.0  15.0    Sandwich
Ceylon          520     250      2     0.0  14.0   Montblank

In [415]:
# 欠損値が一つでもあるデータ（行）を削除
B.dropna()

Price  Volume  Sales  Coffee  Peak    WithMeal
Cocoa           450     300      5     0.0  15.0    Sandwich
Cappuccino      400     250     10     1.0  15.0  Cheesecake
Darjeeling      450     230      7     0.0  13.0    Sandwich
Gyokuro         470     320      3     0.0  13.0    Sandwich
Kona            470     250      4     1.0  14.0   Montblank
Kilimanjaro     500     250      8     1.0  16.0   Montblank
BlueMountain    480     250      6     1.0  16.0   Montblank
CafeAuLait      400     320      6     1.0  14.0   Montblank
EarlGrey        450     250      3     0.0  15.0    Sandwich
Ceylon          520     250      2     0.0  14.0   Montblank

In [461]:
# 選択した列を削除
B.drop(["Peak", "WithMeal"], axis = 1)

Price  Volume  Sales  Coffee
Cocoa           450     300      5     0.0
Cappuccino      400     250     10     1.0
Darjeeling      450     230      7     0.0
Gyokuro         470     320      3     0.0
Kona            470     250      4     1.0
Espresso        420     260      7     1.0
Kilimanjaro     500     250      8     1.0
BlueMountain    480     250      6     1.0
Brazil          550     200      3     1.0
Geisha          600     200      2     1.0
CafeAuLait      400     320      6     1.0
EarlGrey        450     250      3     0.0
Ceylon          520     250      2     0.0

In [466]:
# 選択した行を削除
B.drop(["Espresso", "Brazil", "Geisha"])

Price  Volume  Sales  Coffee  Peak    WithMeal
Cocoa           450     300      5     0.0  15.0    Sandwich
Cappuccino      400     250     10     1.0  15.0  Cheesecake
Darjeeling      450     230      7     0.0  13.0    Sandwich
Gyokuro         470     320      3     0.0  13.0    Sandwich
Kona            470     250      4     1.0  14.0   Montblank
Kilimanjaro     500     250      8     1.0  16.0   Montblank
BlueMountain    480     250      6     1.0  16.0   Montblank
CafeAuLait      400     320      6     1.0  14.0   Montblank
EarlGrey        450     250      3     0.0  15.0    Sandwich
Ceylon          520     250      2     0.0  14.0   Montblank

In [487]:
# 欠損値を平均値で埋める
B.fillna(B["Peak"].mean())

Price  Volume  Sales  Coffee  Peak    WithMeal
Cocoa           450     300      5     0.0  15.0    Sandwich
Cappuccino      400     250     10     1.0  15.0  Cheesecake
Darjeeling      450     230      7     0.0  13.0    Sandwich
Gyokuro         470     320      3     0.0  13.0    Sandwich
Kona            470     250      4     1.0  14.0   Montblank
Espresso        420     260      7     1.0  14.5  Cheesecake
Kilimanjaro     500     250      8     1.0  16.0   Montblank
BlueMountain    480     250      6     1.0  16.0   Montblank
Brazil          550     200      3     1.0  14.5   Montblank
Geisha          600     200      2     1.0  14.5  Cheesecake
CafeAuLait      400     320      6     1.0  14.0   Montblank
EarlGrey        450     250      3     0.0  15.0    Sandwich
Ceylon          520     250      2     0.0  14.0   Montblank

# カテゴリカル変数

In [481]:
# カテゴリカル変数に変換
pd.get_dummies(B)

Price  Volume  Sales  Coffee  Peak  WithMeal_Cheesecake  \
Cocoa           450     300      5     0.0  15.0                    0   
Cappuccino      400     250     10     1.0  15.0                    1   
Darjeeling      450     230      7     0.0  13.0                    0   
Gyokuro         470     320      3     0.0  13.0                    0   
Kona            470     250      4     1.0  14.0                    0   
Espresso        420     260      7     1.0   NaN                    1   
Kilimanjaro     500     250      8     1.0  16.0                    0   
BlueMountain    480     250      6     1.0  16.0                    0   
Brazil          550     200      3     1.0   NaN                    0   
Geisha          600     200      2     1.0   NaN                    1   
CafeAuLait      400     320      6     1.0  14.0                    0   
EarlGrey        450     250      3     0.0  15.0                    0   
Ceylon          520     250      2     0.0  14.0                    0   

              WithMeal_Montblank  WithMeal_Sandwich  
Cocoa                          0                  1  
Cappuccino                     0                  0  
Darjeeling                     0                  1  
Gyokuro                        0                  1  
Kona                           1                  0  
Espresso                       0                  0  
Kilimanjaro                    1                  0  
BlueMountain                   1                  0  
Brazil                         1                  0  
Geisha                         0                  0  
CafeAuLait                     1                  0  
EarlGrey                       0                  1  
Ceylon                         1                  0

# 条件式によるデータの選択

In [416]:
# 条件に一致するデータだけを選択
B[B["Coffee"] == 1]

Price  Volume  Sales  Coffee  Peak    WithMeal
Cappuccino      400     250     10     1.0  15.0  Cheesecake
Kona            470     250      4     1.0  14.0   Montblank
Espresso        420     260      7     1.0   NaN  Cheesecake
Kilimanjaro     500     250      8     1.0  16.0   Montblank
BlueMountain    480     250      6     1.0  16.0   Montblank
Brazil          550     200      3     1.0   NaN   Montblank
Geisha          600     200      2     1.0   NaN  Cheesecake
CafeAuLait      400     320      6     1.0  14.0   Montblank

In [418]:
B[B["Price"] >= 500]

Price  Volume  Sales  Coffee  Peak    WithMeal
Kilimanjaro    500     250      8     1.0  16.0   Montblank
Brazil         550     200      3     1.0   NaN   Montblank
Geisha         600     200      2     1.0   NaN  Cheesecake
Ceylon         520     250      2     0.0  14.0   Montblank

In [456]:
B[B["WithMeal"] == "Sandwich"]

Price  Volume  Sales  Coffee  Peak  WithMeal
Cocoa         450     300      5     0.0  15.0  Sandwich
Darjeeling    450     230      7     0.0  13.0  Sandwich
Gyokuro       470     320      3     0.0  13.0  Sandwich
EarlGrey      450     250      3     0.0  15.0  Sandwich

# データの保存

In [405]:
# データフレームの保存
B.to_csv("../Documents/dataset/hoge_df.csv")

# データのソート

In [425]:
# 売り上げが少ない順にソート
A.sort_values(by = ["Sales"])

Price  Volume  Sales  Coffee  Peak    WithMeal  Color
Geisha          600     200      2     1.0   NaN  Cheesecake    NaN
Ceylon          520     250      2     0.0  14.0   Montblank    NaN
Gyokuro         470     320      3     0.0  13.0    Sandwich    NaN
Brazil          550     200      3     1.0   NaN   Montblank    NaN
EarlGrey        450     250      3     0.0  15.0    Sandwich    NaN
Kona            470     250      4     1.0  14.0   Montblank    NaN
Cocoa           450     300      5     0.0  15.0    Sandwich    NaN
BlueMountain    480     250      6     1.0  16.0   Montblank    NaN
CafeAuLait      400     320      6     1.0  14.0   Montblank    NaN
Darjeeling      450     230      7     0.0  13.0    Sandwich    NaN
Espresso        420     260      7     1.0   NaN  Cheesecake    NaN
Kilimanjaro     500     250      8     1.0  16.0   Montblank    NaN
Cappuccino      400     250     10     1.0  15.0  Cheesecake    NaN

In [426]:
# 売り上げが多い順にソート
A.sort_values(by = ["Sales"], ascending = False)

Price  Volume  Sales  Coffee  Peak    WithMeal  Color
Cappuccino      400     250     10     1.0  15.0  Cheesecake    NaN
Kilimanjaro     500     250      8     1.0  16.0   Montblank    NaN
Darjeeling      450     230      7     0.0  13.0    Sandwich    NaN
Espresso        420     260      7     1.0   NaN  Cheesecake    NaN
BlueMountain    480     250      6     1.0  16.0   Montblank    NaN
CafeAuLait      400     320      6     1.0  14.0   Montblank    NaN
Cocoa           450     300      5     0.0  15.0    Sandwich    NaN
Kona            470     250      4     1.0  14.0   Montblank    NaN
Gyokuro         470     320      3     0.0  13.0    Sandwich    NaN
Brazil          550     200      3     1.0   NaN   Montblank    NaN
EarlGrey        450     250      3     0.0  15.0    Sandwich    NaN
Geisha          600     200      2     1.0   NaN  Cheesecake    NaN
Ceylon          520     250      2     0.0  14.0   Montblank    NaN

In [429]:
# 売り上げが多い順かつ値段が高い順にソート
A.sort_values(by = ["Sales", "Price"], ascending = [False, False])

Price  Volume  Sales  Coffee  Peak    WithMeal  Color
Cappuccino      400     250     10     1.0  15.0  Cheesecake    NaN
Kilimanjaro     500     250      8     1.0  16.0   Montblank    NaN
Darjeeling      450     230      7     0.0  13.0    Sandwich    NaN
Espresso        420     260      7     1.0   NaN  Cheesecake    NaN
BlueMountain    480     250      6     1.0  16.0   Montblank    NaN
CafeAuLait      400     320      6     1.0  14.0   Montblank    NaN
Cocoa           450     300      5     0.0  15.0    Sandwich    NaN
Kona            470     250      4     1.0  14.0   Montblank    NaN
Brazil          550     200      3     1.0   NaN   Montblank    NaN
Gyokuro         470     320      3     0.0  13.0    Sandwich    NaN
EarlGrey        450     250      3     0.0  15.0    Sandwich    NaN
Geisha          600     200      2     1.0   NaN  Cheesecake    NaN
Ceylon          520     250      2     0.0  14.0   Montblank    NaN

In [431]:
# 商品名をアルファベット順に並べ替える
A.sort_index(axis = 0)

Price  Volume  Sales  Coffee  Peak    WithMeal  Color
BlueMountain    480     250      6     1.0  16.0   Montblank    NaN
Brazil          550     200      3     1.0   NaN   Montblank    NaN
CafeAuLait      400     320      6     1.0  14.0   Montblank    NaN
Cappuccino      400     250     10     1.0  15.0  Cheesecake    NaN
Ceylon          520     250      2     0.0  14.0   Montblank    NaN
Cocoa           450     300      5     0.0  15.0    Sandwich    NaN
Darjeeling      450     230      7     0.0  13.0    Sandwich    NaN
EarlGrey        450     250      3     0.0  15.0    Sandwich    NaN
Espresso        420     260      7     1.0   NaN  Cheesecake    NaN
Geisha          600     200      2     1.0   NaN  Cheesecake    NaN
Gyokuro         470     320      3     0.0  13.0    Sandwich    NaN
Kilimanjaro     500     250      8     1.0  16.0   Montblank    NaN
Kona            470     250      4     1.0  14.0   Montblank    NaN

# 統計量の算出

In [443]:
# 各特徴量の合計値
df.sum()

Price     6160
Volume    3330
Sales       66
dtype: int64

In [446]:
# 必要なものだけを取り出す
df.sum()["Price"]

6160

In [447]:
df.sum()[1]

3330

In [448]:
# 平均
df.mean()

Price     473.846154
Volume    256.153846
Sales       5.076923
dtype: float64

In [449]:
# 標準偏差
df.std()

Price     57.812695
Volume    37.977726
Sales      2.498718
dtype: float64

In [450]:
# 最大値
df.max()

Price     600
Volume    320
Sales      10
dtype: int64

In [451]:
# 最小値
df.min()

Price     400
Volume    200
Sales       2
dtype: int64

In [452]:
# 相関係数
df.corr()

Price    Volume     Sales
Price   1.000000 -0.637932 -0.648314
Volume -0.637932  1.000000  0.135101
Sales  -0.648314  0.135101  1.000000

In [459]:
# 平均、標準偏差、四分位数を一度に算出
df.describe()

Price      Volume      Sales
count   13.000000   13.000000  13.000000
mean   473.846154  256.153846   5.076923
std     57.812695   37.977726   2.498718
min    400.000000  200.000000   2.000000
25%    450.000000  250.000000   3.000000
50%    470.000000  250.000000   5.000000
75%    500.000000  260.000000   7.000000
max    600.000000  320.000000  10.000000

# データフレームの作成

In [434]:
# 空のデータフレームを作る
new_df = pd.DataFrame(np.zeros((5, 3)))
new_df

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

In [435]:
# 行や列の名前はリストで入力
new_df = pd.DataFrame(np.zeros((5, 3)), columns = ["Chemistry", "Biology", "Physics"], index = ["Mario", "Kirby", "Pikachu", "Link", "Fox"])
new_df

Chemistry  Biology  Physics
Mario          0.0      0.0      0.0
Kirby          0.0      0.0      0.0
Pikachu        0.0      0.0      0.0
Link           0.0      0.0      0.0
Fox            0.0      0.0      0.0

In [441]:
# データの入力
new_df.loc["Mario", "Chemistry"] = 80
new_df.iloc[1,2] = 100
new_df

Chemistry  Biology  Physics
Mario         80.0      0.0      0.0
Kirby          0.0      0.0    100.0
Pikachu        0.0      0.0      0.0
Link           0.0      0.0      0.0
Fox            0.0      0.0      0.0